### ISSUE TITLE
Is constructor broken?

### ISSUE THREAD

**Issue by AXGKl** [conda/constructor#257]
I can't manage to get constructor working anymore with a recent version of conda.

- I created a clean centos7 vm on digitalocean, just added bzip2.
- Downloaded Miniconda in various versions. 
- Activated them
- conda install constructor
- constructor .  # with a trivial construct yaml

They all fail except when I go back to this version of conda: https://repo.anaconda.com/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh

**Details**

Succesful run with Miniconda3-4.3.21-Linux-x86_64:

<details>
 <summary>Miniconda3-4.3.21-Linux-x86_64</summary>

```
 (root) [root@centos-s-1vcpu-1gb-fra1-01 ~]# constructor -V
constructor version: 1.5.5
(root) [root@centos-s-1vcpu-1gb-fra1-01 ~]# cat construct.yaml 
name: MinicondaX
version: 1.2.3.4 

install_in_dependency_order: True

channels:
  - http://repo.anaconda.com/pkgs/main/

specs:
  - python
  - conda
(root) [root@centos-s-1vcpu-1gb-fra1-01 ~]# constructor --debug .
platform: linux-64
DEBUG:libconda.fetch:channel_urls=('http://repo.anaconda.com/pkgs/main/linux-64/', 'http://repo.anaconda.com/pkgs/main/noarch/')
Fetching package metadata: INFO:stdoutlog:Fetching package metadata: 
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): repo.anaconda.com
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (2): repo.anaconda.com
DEBUG:requests.packages.urllib3.connectionpool:http://repo.anaconda.com:80 "GET /pkgs/main/linux-64/repodata.json.bz2 HTTP/1.1" 301 None
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com
DEBUG:requests.packages.urllib3.connectionpool:http://repo.anaconda.com:80 "GET /pkgs/main/noarch/repodata.json.bz2 HTTP/1.1" 301 None
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): repo.anaconda.com
DEBUG:requests.packages.urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:requests.packages.urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://repo.anaconda.com/pkgs/main/noarch/',) kwargs {'use_cache': False, 'session': <libconda.connection.CondaSession object at 0x7ff4ceb1def0>}
.DEBUG:dotupdate:fetching repodata: args ('http://repo.anaconda.com/pkgs/main/linux-64/',) kwargs {'use_cache': False, 'session': <libconda.connection.CondaSession object at 0x7ff4ceb1def0>}

INFO:stdoutlog:

Solving package specifications: INFO:stdoutlog:Solving package specifications: 
.DEBUG:dotupdate:Solving for ['python', 'conda']
DEBUG:libconda.resolve:Retrieving packages for: [MatchSpec('python'), MatchSpec('conda')]
DEBUG:libconda.resolve: python: pruned from 66 -> 39
DEBUG:libconda.resolve: libgcc-ng: pruned from 8 -> 7
DEBUG:libconda.resolve: libstdcxx-ng: pruned from 8 -> 7
DEBUG:libconda.resolve: openssl: pruned from 16 -> 13
DEBUG:libconda.resolve: libedit: pruned from 3 -> 2
DEBUG:libconda.resolve: ncurses: pruned from 4 -> 2
DEBUG:libconda.resolve: conda: pruned from 129 -> 127
DEBUG:libconda.resolve: urllib3: pruned from 28 -> 16
DEBUG:libconda.resolve: readline: pruned from 4 -> 3
.DEBUG:dotupdate:Checking satisfiability
DEBUG:libconda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package removal metric: 0
DEBUG:libconda.logic:Beginning peak minimization
DEBUG:libconda.logic:Initial range (0,0)
DEBUG:libconda.logic:Bisection attempt: (0,0), (5716+162) clauses
DEBUG:libconda.logic:Bisection success, new range=(0,0)
DEBUG:libconda.logic:Final peak objective: 0
DEBUG:libconda.logic:Beginning peak minimization
DEBUG:libconda.logic:Initial range (0,0)
DEBUG:libconda.logic:Bisection attempt: (0,0), (5878+23) clauses
DEBUG:libconda.logic:Bisection success, new range=(0,0)
DEBUG:libconda.logic:Final peak objective: 0
.DEBUG:dotupdate:Initial package version/build metrics: 0/0
DEBUG:libconda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Track feature count: 0
DEBUG:libconda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package feature count: 0
DEBUG:libconda.logic:Beginning peak minimization
DEBUG:libconda.logic:Initial range (0,1)
DEBUG:libconda.logic:Bisection attempt: (0,0), (5901+379) clauses
DEBUG:libconda.logic:Bisection success, new range=(0,0)
DEBUG:libconda.logic:Final peak objective: 0
DEBUG:libconda.logic:Beginning peak minimization
DEBUG:libconda.logic:Initial range (0,2)
DEBUG:libconda.logic:Bisection attempt: (0,0), (6280+78) clauses
DEBUG:libconda.logic:Bisection success, new range=(0,0)
DEBUG:libconda.logic:Final peak objective: 0
.DEBUG:dotupdate:Additional package version/build metrics: 0/0
DEBUG:libconda.logic:Beginning sum minimization
DEBUG:libconda.logic:Initial range (0,13)
DEBUG:libconda.logic:Bisection attempt: (0,12), (6358+6891) clauses
DEBUG:libconda.logic:Bisection success, new range=(0,12)
DEBUG:libconda.logic:Bisection attempt: (0,6), (6358+3747) clauses
DEBUG:libconda.logic:Bisection failure, new range=(7,12)
DEBUG:libconda.logic:Bisection attempt: (7,9), (6358+5410) clauses
DEBUG:libconda.logic:Bisection failure, new range=(10,12)
DEBUG:libconda.logic:Bisection attempt: (10,11), (6358+6448) clauses
DEBUG:libconda.logic:Bisection failure, new range=(12,12)
DEBUG:libconda.logic:Bisection attempt: (12,12), (6358+6937) clauses
DEBUG:libconda.logic:Bisection success, new range=(12,12)
DEBUG:libconda.logic:Final sum objective: 12
DEBUG:libconda.logic:New peak objective: 1
.DEBUG:dotupdate:Weak dependency count: 12
.DEBUG:dotupdate:Looking for alternate solutions

Warning: 2 possible package resolutions (only showing differing packages):
  - yaml-0.1.7-had09818_2.tar.bz2
  - yaml-0.1.7-h014fa73_2.tar.bz2INFO:stdoutlog:
Warning: 2 possible package resolutions (only showing differing packages):
  - yaml-0.1.7-had09818_2.tar.bz2
  - yaml-0.1.7-h014fa73_2.tar.bz2

INFO:stdoutlog:


Reading: /root/s3/lib/python3.6/site-packages/constructor/header.sh
Successfully created '/root/MinicondaX-1.2.3.4-Linux-x86_64.sh'.
(root) [root@centos-s-1vcpu-1gb-fra1-01 ~]# 
```   

</details>

Newer Versions of conda:

<details>
 <summary>Fail log</summary>

```
    (base) [root@centos-s-1vcpu-1gb-fra1-01 ~]# source /root/miniconda3/etc/profile.d/conda.sh 
(base) [root@centos-s-1vcpu-1gb-fra1-01 ~]# constructor -V
constructor version: 2.3.0
(base) [root@centos-s-1vcpu-1gb-fra1-01 ~]# constructor --debug .
platform: linux-64
DEBUG:conda.core.solve:solving prefix /constructor/no-environment
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec("python"), MatchSpec("conda")})
  prune: <auxlib._Null object at 0x7f218fa03518>
Collecting package metadata (repodata.json): - DEBUG:conda.core.package_cache_data:package cache directory '/root/.conda/constructor/linux-64' writable: True
DEBUG:conda.core.subdir_data:Using cached repodata for http://repo.anaconda.com/pkgs/main/linux-64/repodata.json at /root/.conda/constructor/linux-64/cache/ddd2bc08.json. Timeout in 5 sec
DEBUG:conda.core.subdir_data:found pickle file /root/.conda/constructor/linux-64/cache/ddd2bc08.q
DEBUG:conda.core.subdir_data:Using cached repodata for http://repo.anaconda.com/pkgs/main/noarch/repodata.json at /root/.conda/constructor/linux-64/cache/a53f9773.json. Timeout in 5 sec
DEBUG:conda.core.subdir_data:found pickle file /root/.conda/constructor/linux-64/cache/a53f9773.q
done
Solving environment: / DEBUG:conda.resolve:Retrieving packages for: 
  - conda
  - python
DEBUG:conda.resolve:libgcc-ng: pruned from 8 -> 7
DEBUG:conda.resolve:libstdcxx-ng: pruned from 8 -> 7
\ DEBUG:conda.resolve:conda: pruned from 129 -> 127
/ DEBUG:conda.resolve:urllib3: pruned from 28 -> 16
| DEBUG:conda.core.solve:specs_map with targets: OrderedDict()
DEBUG:conda.resolve:Checking if the current environment is consistent
DEBUG:conda.core.solve:inconsistent precs: None
DEBUG:conda.core.solve:final specs to add: 
  - conda
  - python
DEBUG:conda.resolve:Solving for: 
  - conda
  - python
DEBUG:conda.resolve:Solve: Getting reduced index of compliant packages
DEBUG:conda.resolve:Solve: determining satisfiability
/ DEBUG:conda.resolve:Using SAT solver interface 'pycosat'.
/ DEBUG:conda.resolve:gen_clauses returning with clause count: 13647
DEBUG:conda.resolve:generate_spec_constraints returning with clause count: 13647
DEBUG:conda.common.logic:Invoking SAT with clause count: 13649
- DEBUG:conda.resolve:Solve: minimize removed packages
DEBUG:conda.resolve:Solve: maximize versions of requested packages
DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.common.logic:Invoking SAT with clause count: 13838
DEBUG:conda.common.logic:Final peak objective: 0
DEBUG:conda.resolve:Initial package channel/version metric: 0/0
DEBUG:conda.resolve:Solve: minimize track_feature count
DEBUG:conda.resolve:generate_feature_count returning with clause count: 13838
DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.resolve:Track feature count: 0
DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.resolve:Package misfeature count: 0
DEBUG:conda.resolve:Solve: maximize build numbers of requested packages
DEBUG:conda.common.logic:Invoking SAT with clause count: 13886
DEBUG:conda.common.logic:Final peak objective: 0
DEBUG:conda.resolve:Initial package build metric: 0
DEBUG:conda.resolve:Solve: prefer arch over noarch for requested packages
DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.resolve:Noarch metric: 0
DEBUG:conda.resolve:Solve: minimize number of optional installations
DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.resolve:Optional package install metric: 0
DEBUG:conda.resolve:Solve: minimize number of necessary upgrades
DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.resolve:Dependency update count: 0
DEBUG:conda.resolve:Solve: maximize versions and builds of indirect dependencies.  Prefer arch over noarch where equivalent.
\ DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.common.logic:Invoking SAT with clause count: 14748
DEBUG:conda.common.logic:Final peak objective: 0
DEBUG:conda.common.logic:Invoking SAT with clause count: 14880
DEBUG:conda.common.logic:Final peak objective: 0
DEBUG:conda.common.logic:Empty objective, trivial solution
DEBUG:conda.resolve:Additional package channel/version/build/noarch metrics: 0/0/0/0
DEBUG:conda.resolve:Solve: prune unnecessary packages
DEBUG:conda.common.logic:Invoking SAT with clause count: 18631
DEBUG:conda.common.logic:Invoking SAT with clause count: 18762
| DEBUG:conda.common.logic:Final sum objective: 39
DEBUG:conda.common.logic:New peak objective: 1
DEBUG:conda.resolve:Weak dependency count: 39
DEBUG:conda.common.logic:Invoking SAT with clause count: 18763
DEBUG:conda.common.logic:Invoking SAT with clause count: 19523
DEBUG:conda.common.logic:Invoking SAT with clause count: 19195
DEBUG:conda.common.logic:Invoking SAT with clause count: 18876
DEBUG:conda.common.logic:Final peak objective: 2
- DEBUG:conda.common.logic:Invoking SAT with clause count: 65105
| DEBUG:conda.common.logic:Invoking SAT with clause count: 44053
/ DEBUG:conda.common.logic:Invoking SAT with clause count: 55479
\ DEBUG:conda.common.logic:Invoking SAT with clause count: 60814
| DEBUG:conda.common.logic:Invoking SAT with clause count: 63387
- DEBUG:conda.common.logic:Invoking SAT with clause count: 62408
| DEBUG:conda.common.logic:Invoking SAT with clause count: 63302
DEBUG:conda.common.logic:Final sum objective: 31
DEBUG:conda.common.logic:New peak objective: 2
DEBUG:conda.resolve:Timestamp metric: 31
DEBUG:conda.resolve:Looking for alternate solutions
DEBUG:conda.common.logic:Invoking SAT with clause count: 63303
done
DEBUG:conda.core.solve:solved prefix /constructor/no-environment
  solved_linked_dists:
    defaults::ca-certificates-2019.5.15-0
    defaults::libgcc-ng-9.1.0-hdf63c60_0
    defaults::libstdcxx-ng-9.1.0-hdf63c60_0
    defaults::bzip2-1.0.6-h14c3975_5
    defaults::libffi-3.2.1-hd88cf55_4
    defaults::lz4-c-1.8.1.2-h14c3975_0
    defaults::lzo-2.10-h49e0be7_2
    defaults::ncurses-6.1-he6710b0_1
    defaults::openssl-1.1.1c-h7b6447c_1
    defaults::xz-5.2.4-h14c3975_4
    defaults::yaml-0.1.7-had09818_2
    defaults::zlib-1.2.11-h7b6447c_3
    defaults::libedit-3.1.20181209-hc058e9b_0
    defaults::libxml2-2.9.9-hea5a465_1
    defaults::readline-7.0-h7b6447c_5
    defaults::tk-8.6.8-hbc83047_0
    defaults::zstd-1.3.7-h0b5b093_0
    defaults::libarchive-3.3.3-h5d8350f_5
    defaults::sqlite-3.28.0-h7b6447c_0
    defaults::python-3.7.3-h0371630_0
    defaults::asn1crypto-0.24.0-py37_0
    defaults::certifi-2019.6.16-py37_0
    defaults::chardet-3.0.4-py37_1
    defaults::idna-2.8-py37_0
    defaults::pycosat-0.6.3-py37h14c3975_0
    defaults::pycparser-2.19-py37_0
    defaults::pysocks-1.7.0-py37_0
    defaults::python-libarchive-c-2.8-py37_6
    defaults::ruamel_yaml-0.15.46-py37h14c3975_0
    defaults::six-1.12.0-py37_0
    defaults::tqdm-4.32.1-py_0
    defaults::cffi-1.12.3-py37h2e261b9_0
    defaults::conda-package-handling-1.3.10-py37_0
    defaults::setuptools-41.0.1-py37_0
    defaults::cryptography-2.7-py37h1ba5d50_0
    defaults::wheel-0.33.4-py37_0
    defaults::pip-19.1.1-py37_0
    defaults::pyopenssl-19.0.0-py37_0
    defaults::urllib3-1.24.2-py37_0
    defaults::requests-2.22.0-py37_0
    defaults::conda-4.7.5-py37_0

DEBUG:conda.core.package_cache_data:package cache directory '/root/.conda/constructor/linux-64' writable: True
Checking for duplicate files ...
Warning: Files 'share/terminfo/2/2621A', 'share/terminfo/2/2621a' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/E/Eterm', 'share/terminfo/e/eterm' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/E/Eterm-color', 'share/terminfo/e/eterm-color' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/l/lft-pc850', 'share/terminfo/L/LFT-PC850' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/n/ncr260vt300wpp', 'share/terminfo/N/NCR260VT300WPP' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/n/ncrvt100wpp', 'share/terminfo/N/NCRVT100WPP' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P12', 'share/terminfo/p/p12' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P12-M', 'share/terminfo/p/p12-m' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/p/p12-m-w', 'share/terminfo/P/P12-M-W' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P12-W', 'share/terminfo/p/p12-w' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/p/p14', 'share/terminfo/P/P14' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P14-M', 'share/terminfo/p/p14-m' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P14-M-W', 'share/terminfo/p/p14-m-w' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/p/p14-w', 'share/terminfo/P/P14-W' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P4', 'share/terminfo/p/p4' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/p/p5', 'share/terminfo/P/P5' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/p/p7', 'share/terminfo/P/P7' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/p/p8', 'share/terminfo/P/P8' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/p/p8-w', 'share/terminfo/P/P8-W' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P9', 'share/terminfo/p/p9' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P9-8', 'share/terminfo/p/p9-8' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P9-8-W', 'share/terminfo/p/p9-8-w' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/P/P9-W', 'share/terminfo/p/p9-w' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/h/hp2621A', 'share/terminfo/h/hp2621a' found in the package(s): ncurses-6.1-he6710b0_1.conda
Warning: Files 'share/terminfo/h/hp70092a', 'share/terminfo/h/hp70092A' found in the package(s): ncurses-6.1-he6710b0_1.conda
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): repo.anaconda.com:80
DEBUG:urllib3.connectionpool:http://repo.anaconda.com:80 "GET /pkgs/main/linux-64/repodata.json HTTP/1.1" 301 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/repodata.json HTTP/1.1" 200 None
DEBUG:conda.core.subdir_data:
>>GET /pkgs/main/linux-64/repodata.json HTTPS
> User-Agent: conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/3.10.0-957.12.2.el7.x86_64 centos/7.6.1810 glibc/2.17
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive

<<HTTPS 200 OK
< Age: 357959
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4ef77a725da2275a-FRA
< Content-Encoding: gzip
< Content-Type: application/json
< Date: Mon, 01 Jul 2019 09:50:53 GMT
< ETag: W/"a725c0e868a4be03c9efb546db94fed3-2"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Mon, 01 Jul 2019 09:51:23 GMT
< Last-Modified: Thu, 27 Jun 2019 06:21:20 GMT
< Server: cloudflare
< Set-Cookie: __cfduid=d2ef248e9f1e2a67b7c87984492c1ace51561974653; expires=Tue, 30-Jun-20 09:50:53 GMT; path=/; domain=.anaconda.com; HttpOnly; Secure
< Transfer-Encoding: chunked
< Vary: Accept-Encoding
< x-amz-id-2: 1uQWKDf+1wPr9oMdlbAeuwRID9tOFxoxJaDPKPvc7zOjPygt1RkpWzideGWZ47n8bxAx+XilNys=
< x-amz-request-id: 31C41F5EBE128DDC
< x-amz-version-id: RpZGC87a0p.da4OaxYCtdSoxcia.6FQ2
< Connection: keep-alive
< Elapsed: 00:00.064492

{ 'info': {'subdir': 'linux-64'},
  'packages': { '_ipyw_jlab_nb_ext_conf-0.1.0-py27_0.tar.bz2': { 'build': 'py27_0',
                                                                 'build_number': 0,
                                                      


DEBUG:urllib3.connectionpool:http://repo.anaconda.com:80 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 301 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 200 None
DEBUG:conda.core.subdir_data:
>>GET /pkgs/main/noarch/repodata.json HTTPS
> User-Agent: conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/3.10.0-957.12.2.el7.x86_64 centos/7.6.1810 glibc/2.17
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Cookie: __cfduid=d2ef248e9f1e2a67b7c87984492c1ace51561974653

<<HTTPS 200 OK
< Age: 357984
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4ef77ad38c0a275a-FRA
< Content-Encoding: gzip
< Content-Type: application/json
< Date: Mon, 01 Jul 2019 09:51:09 GMT
< ETag: W/"d200c5f4aa3959cb789ef5812fe3aeb0"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Mon, 01 Jul 2019 09:51:39 GMT
< Last-Modified: Thu, 27 Jun 2019 06:21:42 GMT
< Server: cloudflare
< Transfer-Encoding: chunked
< Vary: Accept-Encoding
< x-amz-id-2: va4pjXk3Xr7syus2ZImAFXVt73QSoH4V0a5GN8723a3tUbUBraMyB9AqqQxw2XbbQjkT2Kez6gc=
< x-amz-request-id: C159EA0B3CBC5D51
< x-amz-version-id: tj0liLiqy_p2p5uurUrbuejYf.3IWfoe
< Connection: keep-alive
< Elapsed: 00:00.020968

{ 'info': {'subdir': 'noarch'},
  'packages': { 'affine-2.1.0-pyh128a3a6_1.tar.bz2': { 'build': 'pyh128a3a6_1',
                                                       'build_number': 1,
                                                       'depends': ['py


Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/conda/models/dist.py", line 207, in parse_dist_name
    version = parts[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/root/miniconda3/lib/python3.7/site-packages/constructor/main.py", line 128, in main_build
    create(info, verbose=verbose)
  File "/root/miniconda3/lib/python3.7/site-packages/constructor/shar.py", line 81, in create
    preconda_write_files(info, tmp_dir)
  File "/root/miniconda3/lib/python3.7/site-packages/constructor/preconda.py", line 137, in write_files
    write_conda_meta(info, dst_dir, final_urls_md5s)
  File "/root/miniconda3/lib/python3.7/site-packages/constructor/preconda.py", line 155, in write_conda_meta
    dists = tuple(Dist(url) for url, _ in final_urls_md5s)
  File "/root/miniconda3/lib/python3.7/site-packages/constructor/preconda.py", line 155, in <genexpr>
    dists = tuple(Dist(url) for url, _ in final_urls_md5s)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/models/dist.py", line 48, in __call__
    dist = Dist.from_string(value)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/models/dist.py", line 182, in from_string
    dist_details = cls.parse_dist_name(original_dist)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/models/dist.py", line 217, in parse_dist_name
    raise CondaError("dist_name is not a valid conda package: %s" % original_string)
conda.CondaError: dist_name is not a valid conda package: None
(base) [root@centos-s-1vcpu-1gb-fra1-01 ~]# 
```

</details>

- I tried this on different OSes and different versions of conda. *sometimes* it works the first time but then fails all subsequent runs.

- I get the error even when I run the exact steps  of your travis file.

- When I run in --debug mode I have the feeling that the `DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/repodata.json HTTP/1.1" 200 None` step takes far longer, maybe it goes into timeout ?

- I could invest some time and found that the error is cause from Nones in this structure, in `def write_conda_meta`:
![image](https://user-images.githubusercontent.com/9989548/60427701-86a99980-9bf7-11e9-8ebb-e0424ce52d40.png)

- I forked constructor and triggered a travis run. Same error on all combinations:
![image](https://user-images.githubusercontent.com/9989548/60431948-4fd88100-9c01-11e9-95e8-29bfec3c254a.png)
travis console shot with the (same) error:
![image](https://user-images.githubusercontent.com/9989548/60432010-74345d80-9c01-11e9-8092-1cd5e6769a4f.png)

**Comment by newville** [comment]
@AXGKl I can confirm this on OSX as well, and with github master branch  It appears that the "fetch conda packages" routines are getting lots on `None`s.   I'm not entirely sure why but it looks like it may be due to repo locations being moved around, or it might be related to the move away from `bzip2`.

The "find conda packages" steps can be fixed by replacing 

```
_urls = [(pc_rec.url, pc_rec.md5) for pc_rec in pc_recs]
```

at https://github.com/conda/constructor/blob/16b5021a725d13554dd5681f6395c97a38a5568f/constructor/fcp.py#L206

with 

```
_urls = []
    for pc_rec in pc_recs:
        if pc_rec.url is not None:
            _urls.append((pc_rec.url, pc_rec.md5))
```

though I don't know if that is the preferred solution.....

For me, this solves the problem of *finding* the packages and it constructs a shell script.   Unfortunately, that installer package does not run (see #258).

**Comment by nehaljwani** [comment]
Try downgrading conda to 4.5 . The code here is probably not complaint with 4.6+

**Comment by AXGKl** [comment]
@nehaljwani: Nope. Same error with a clean Miniconda3-4.5.12-Linux-x86_64.sh.
@newville: Thanks for the hint - bypassing all with .url = None gets me to an installer - but, as you report in #258, that installer does not work due to .conda packages in /pkgs folder being created....

I'm getting a little nervous since I could not find any workaround getting our product install process running again.

**Comment by nehaljwani** [comment]
@AXGKl Make sure that conda is not updated to 4.6+ just before running constructor. I'm working constructor v3 which is going to support .conda and .tar.bz2 and also noarch.

**Comment by newville** [comment]
@nehaljwani  Thanks -- downgrading to conda 4.5.13 *did* solve this for me.   To be clear, I did this (tested so far only onOSX):  
  1. wipe completely and reinstall Anaconda3-2019.03-MacOSX-x86_64.sh
  2. `conda install conda=4.5.13`
  3. install conda constructor from git master branch with `python setup.py install`.

Then I can build one of the examples (osxpkgtest) and install it.

Anaconda3-2019.3 comes with conda 4.6.11, and `conda update --all` will install 4.7.5.   
There has not been a release of constructor in nearly eight months.   I am very nervous about needing to use conda 4.5.13.  It's not so much that is old, but that if conda is being updated in backward incompatible ways so quickly such that other tools **from conda organization** cannot keep up and are six months behind, it seems possible that something is structurally wrong, either with the code or the organization.  Or maybe the problem just got noticed and will be fixed tomorrow.  From far away, it is very hard to tell.  But, it sort of looks like changes to conda that break constructor are not viewed as show-stoppers.

It would be really helpful if one of the main developers to give some sense of how much of a priority or interest this project is in the `conda` universe, or what other tools might be used in its place?  It has been incredibly useful to me, but I'm somewhat unsure about well supported it will be going forward. (Thanks!)

**Comment by AXGKl** [comment]
@newville: Whew, your way via pip to prevent conda upgrades did the job, at least the example yaml file works on linux as well.  Hope I get the build pipeline with our spec up as well, commiting and testing those necessary changes, bypassing our QA. Not exactly nice.).

@nehaljwani : It's a free tool and it is unique in what it does - but the organization has to see that this tool is perceived as **an integral component of the conda ecosystem** - and not break it at will. I think I remember e.g. Kale Franz promoting it in various occations and it was a big argument in my organziation to prefer conda over other other, faster v.env tools and/or containers.
I'm full backing that statements of @newville.
The organziation has to see that this tool is used in production build processes and not just by "crazy scientists" (I was one in my previous live and even back then I would have gone crazy). 
All the best for version 3 and any information about landing times would be greatly appreciated. Not your fault, all that.

**Comment by msarahan** [comment]
There is a private fork of constructor that we use to build Anaconda and Miniconda installers.  We haven't done a good job of bringing changes there back into constructor.  Nehal is working on that with this next series. (version 3).

We don't break many things intentionally.  As @newville points out, we need better integration testing.  As you might imagine, we have more things to do than hours to spend doing them.  We have to prioritize by many things, including the level of effort that something will take, how many people need it, whether any of the people who need it are paying for it, how it will contribute to our enterprise product, etc.  Many things will suffer and will not get done, or will be done poorly.  What is integral to you may not end up high in that order, unfortunately.  One of the great things about this project, though, is that you need not depend completely on us.  It's open source.  You can fix it yourself, and even give your improvements back.  Perhaps helping to develop better integration tests would be a valuable first contribution.

**Comment by AXGKl** [comment]
@msarahan understood, especially the commercial prios, you need to pay your rents as well in the end.
Fun fact regarding this one: *Perhaps helping to develop better integration tests would be a valuable first contribution.*:  I was curious why the breakage was not seen by your integration tests on travis and forked it to understand better where the gaps are - but guess what; The testsuite IS actually pretty good - you just did not trigger it. I got the same error on travis. 
=> If you would push once a week a test commit you would already see the breakage, right now.

**Comment by newville** [comment]
@msarahan  We're all overworked and we understand that you are too. We're also all committed to using python and open source tools for scientific work.  And we appreciate the efforts by you and @nehaljwani and all the people at Anaconda.

> There is a private fork of constructor that we use to build Anaconda and Miniconda installers.
> We haven't done a good job of bringing changes there back into constructor.
> Nehal is working on that with this next series. (version 3).

Hm, by design we would see no evidence of work done on a private repository.

> We don't break many things intentionally.

I am glad to hear that.  I hope that you see that constructor is broken because of changes to conda. 
It should not be surprising to the developers that the changes to conda would break constructor and Github Issues suggest that you all have known about the breakage for awhile.  

The workaround here is "use conda 4.5".  That is kind of six months and 19 releases ago.  After many days of struggling, I have gotten this get constructor to work again with 4.5.13 for my non-trivial packaging project.  It requires being vigilant that `conda` is not automatically updated.  

Of course, it does not take advantage of changes to conda (that must have value) and is probably not sustainable.   I've used Python for scientific work for a long time.  I have been happy to use Anaconda.  But there is a very real danger that you are driving people away. 

> As @newville points out, we need better integration testing.

Yes, it looks like all of the conda tools need better testing, including integration testing.  It also looks like they may need better communication between projects.  From where I sit, `conda` looks like a complete mess.   I do hope you and others at Anaconda can turn it around.

> As you might imagine, we have more things to do than hours to spend doing them. We have to prioritize by many things, including the level of effort that something will take, how many people need it, whether any of the people who need it are paying for it, how it will contribute to our enterprise product, etc. Many things will suffer and will not get done, or will be done poorly. What is integral to you may not end up high in that order, unfortunately.

Yeah, I do actually get the challenges of resource and time management and that sometimes it is inevitable that things break unintentionally.  I also know that the reaction to hearing reports of such breakage is often as important to the breakage itself.  That is, saying "I/We are too busy to fix something that I/we broke" will be noticed.   Really, we're on your side, but it is possible you might not recognize that raising issues here *is* trying to help you and that *not raising* these issues would be worse for you.

FWIW, I was once a paying customer as part of a support contract with a national lab.  The contract expired and there wasn't enough enthusiasm for the actual support received among those of us at the lab actually paying for that support.

> One of the great things about this project, though, is that you need not depend completely on us. It's open source. You can fix it yourself and even give your improvements back. Perhaps helping to develop better integration tests would be a valuable first contribution

I have submitted PRs to `constructor`, so it would not be my first contribution. I have made some further improvements in my own fork.  Should I be motivated to make a PR to a project that appears unmaintained?  

You started out by saying that you have private repos of constructor.  You also give the corporate line of "we have priorities set by paying customers" with "we" meaning "Anaconda" not "the community of developers working on conda".  Again, we all understand this and it is fine.  But telling us these tools are being developed in-house in private repositories, that is actually not open, and is anti-inspiring for making contributions to what appears to be an unmaintained and outdated public repo.

No matter how open these codes really are, `conda` had 19 releases and some fundamental changes in the six months since the last release of `constructor`. You all must have realized would break constructor and you haven't fixed that, hopefully "yet".

**Comment by nehaljwani** [comment]
@newville @AXGKl Please help test the v3 branch on this repo. xref: https://github.com/conda/constructor/issues/86#issuecomment-510924775

**Comment by AXGKl** [comment]
@nehaljwani  - ok, I'll do over weekend, will ping back early next week.

**Comment by newville** [comment]
@nehaljwani Can you give some indication of what v3 is meant to do?  
Like, is it meant to work with conda 4.7.5? 
Is it meant to work with .conda package format?

**Comment by nehaljwani** [comment]
@newville Yes, it is meant to work with Conda 4.7 and yes it works with .conda packages and it also supports noarch packages

**Comment by AXGKl** [comment]
@nehaljwani:
First of all: Good job, the installer went through, we have our build pipeline back :+1: 
Since it took me while to find out I desribe what I did to get to an installer of our product again:
All for Linux:

1. Download  conda-latest-linux-64.exe[1] from https://repo.anaconda.com/pkgs/misc/conda-execs/. No need to mess with it or try to activate (which does not yet work on linux), it's only required for a constructor run. 
2. git clone constructor, checkout branch v3
3. Then activate a working Miniconda, e.g. 4.6.14 on my test machine. 
4. `pip install -e .`  within the constructor v3 directory, so `constructor` reports "constructor v3.0.0"
5. Then you can run constructor like always, except that you provide the downloaded conda.exe  from step 1 as `--conda-exe` argument.

@nehaljwani : For now I'm glad the old construct.yaml works w/o changes and I 'only' have to include the steps above into the build process. It's a pretty complex build flow, including the creation of a local fake channel,  with exported docker filesystems, packaged as conda so the constructor includes them - and it all works again. I did not yet try the noarch format or their new .conda format. 

Thanks again. Lesson learned for me is that I check in *every* tool from upstream. Breaking change avoidance seems not to be their top prio, can safely say that after a year or so in that ecosystem...
 
[1] That name is pretty telling about their prios, OS wise.

**Comment by mingwandroid** [comment]
@AXGKI, thanks for the mostly really nice, helpful comment. I do however take issue with:

> [1] That name is pretty telling about their prios, OS wise.

Completely untrue. The focus of this work has been to make conda into a single static executable, that was the crux to noarch and .conda support (and large cleanup and removal of redundancy from constructor that this allows). `.exe` means `executable`, no more, no less.

Having worked with them for some years, I truly believe the Anaconda Distribution team members (and conda-forge) care about and love (and hate sometimes in equal measure) all the 3 major OSes and all the major Linux architectures in *equal* measure.

**Comment by mingwandroid** [comment]
> Breaking change avoidance seems not to be their top prio, can safely say that after a year or so in that ecosystem

Breakling change is as terrible for us as it is for anyone, however you should be congnizant that we only need to use constructor about 10 or 20 times a year and it is only at those points where it is essential that it works for us. We could've elected not to release the source too.

Now I'm not defending that as great s/w development practice, but we've a small team, we have lots to do and well, please roll up your sleives instead of berating us. We've not made many promises around constructor other than "we will keep it working for us as best we can and consider any PRs".

**Comment by AXGKl** [comment]
@mingwandroid : 
Thanks. Regarding the .exe:

> [1] That name is pretty telling about their prios, OS wise.

Sorry, that was a shot w/o thinking.
Due to a failure running the constructed artifact at the first try I've read a little into it and saw statements like `CONDA_EXEC="$PREFIX/conda.exe"`, so I thought first the failure is on your side, not detecting the OS correctly or so :-) It's just a strange name for an ELF binary, checked my laptop, to verify. 

> We've not made many promises around constructor other than "we will keep it working for us as best we can and consider any PRs".
This is tough to learn. I do not follow each and every announcement anywhere around conda - but I perceived it as an integral tool of the ecosystem and integrated it into a product build pipeline. At least I was hoping that a certain *fixed* version, when running today, will run also tomorrow. Knowing that disclaimer helps me to re-arrange the build accordingly, checking in all involved tools and packages into our repos. 
Thanks again.

**Comment by mingwandroid** [comment]
> This is tough to learn. I do not follow each and every announcement anywhere around conda - but I perceived it as an integral tool of the ecosystem and integrated it into a product build pipeline. At least I was hoping that a certain fixed version, when running today, will run also tomorrow. Knowing that disclaimer helps me to re-arrange the build accordingly, checking in all involved tools and packages into our repos

Indeed, we should document things better, PRs welcome!

**Comment by nehaljwani** [comment]
If I didn't use a single name for the conda executable everywhere, I would've to maintain a variable everywhere (in the python code and and a parameterized one in header.sh). So I just took the easier path.

**Comment by AXGKl** [comment]
@nehaljwani: I left windows a few decades ago, but from what I remember:
If I did not know conda, I would have declared anyone, coming up with the idea of creating a general purpose, native binary package management system, with command line compat for both, *nix AND windows, as next to insane.
Not that I hate windows or so but the command line is so different.

Maybe with recent MS additions into their OS you can in mid terms, drop a lot of compatibilty work, we'll see...:-)

**Comment by newville** [comment]
@nehaljwani  v3 worked for me for a simple example on MacOS but failed for me with a more complex example, which gave

```
platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done
Checking for duplicate files ...
Error: File 'lib/python3.7/site-packages/setuptools.pth' found in multiple packages: anaconda-client-1.7.2-py37_0.conda, silx-0.10.1-py37h39e3cac_0.tar.bz2
```
is that a separate issue?

Also, why is the location of `conda` now a required argument?    I would have thought that could have been determined from `constructor/conda_interface.py`.

**Comment by nehaljwani** [comment]
@newville The issue you are facing is not new. The duplicate check is same as before. If you want to get around that, either fix your packages to not have the same file, or use the key: `ignore_duplicate_files: True`

The location of conda is now a requirement since constructor v3 gets rid of install.py (which tried to replicate the logic of installation of conda packages) and instead uses conda itself to install the packages, which takes care of multiple things like support for noarch, installation in order, etc. I am also working on releasing how those conda executable files were made.

One of my future goals is to get rid of `conda_interface` too, but that will require some functionality to be exposed by Conda in the form of commands, which needs more work.

**Comment by newville** [comment]
@nehaljwani OK, adding `ignore_duplicate_files: True` almost worked, in the sense that I go to a new error.  Now I'm getting:

```
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to /Users/Newville/.conda/constructor/osx-64/built_pkgs/user_postinstall.pkg
pkgbuild: Inferring bundle components from contents of /Users/Newville/.conda/constructor/osx-64/package_root
pkgbuild: Writing new component property list to /Users/Newville/.conda/constructor/osx-64/built_pkgs/apreinstall.plist
pkgbuild: Reading components from /Users/Newville/.conda/constructor/osx-64/built_pkgs/apreinstall.plist
pkgbuild: Adding top-level preinstall script
pkgbuild: Wrote package to /Users/Newville/.conda/constructor/osx-64/built_pkgs/apreinstall.pkg
productbuild: Wrote synthesized distribution to /Users/Newville/.conda/constructor/osx-64/built_pkgs/distribution.xml
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/spyder-kernels.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/jupyterlab_server.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/spyder.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/widgetsnbextension.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/ipywidgets.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/jupyterlab.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/jupyter.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/anaconda.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/asteval.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/bokeh.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/bottleneck.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/h5py.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/imageio.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/matplotlib.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/mkl-service.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/mkl_fft.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/numpy.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/numba.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/numexpr.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pandas.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pycifrw.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pyepics.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pyqtgraph.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pytest-arraydiff.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pytest-doctestplus.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pywavelets.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/scipy.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/silx.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/tifffile.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/uncertainties.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/wxmplot.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/bkcharts.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/dask.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/lmfit.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/patsy.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/peakutils.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pyfai.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pytables.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pytest-astropy.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/scikit-image.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/scikit-learn.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/astropy.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/dioptas.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/statsmodels.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/tomopy.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/seaborn.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/xraylarch.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/_anaconda_depends.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/postextract.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/pathupdate.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/user_postinstall.pkg could not be loaded
productbuild: warning: package /Users/Newville/.conda/constructor/osx-64/built_pkgs/conda.exe.pkg could not be loaded
productbuild: error: Cannot write product to "tmp.pkg". (The operation couldn\U2019t be completed. (NSCocoaErrorDomain error 256.))
I/O error : Too many open files
I/O error : Too many open files
error : xmlNewTextWriterFilename : cannot open uri
error : xmlTextWriterStartDocument : invalid writer!
error : xmlTextWriterEndDocument : invalid writer!
Traceback (most recent call last):
  File "/Users/Newville/anaconda3/bin/constructor", line 11, in <module>
    load_entry_point('constructor==3.0.0', 'console_scripts', 'constructor')()
  File "/Users/Newville/anaconda3/lib/python3.7/site-packages/constructor/main.py", line 229, in main
    dry_run=args.dry_run, conda_exe=args.conda_exe)
  File "/Users/Newville/anaconda3/lib/python3.7/site-packages/constructor/main.py", line 133, in main_build
    create(info, verbose=verbose)
  File "/Users/Newville/anaconda3/lib/python3.7/site-packages/constructor/osxpkg.py", line 284, in create
    "tmp.pkg",
  File "/Users/Newville/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['productbuild', '--distribution', '/Users/Newville/.conda/constructor/osx-64/built_pkgs/distribution.xml', '--package-path', '/Users/Newville/.conda/constructor/osx-64/built_pkgs', '--identifier', 'xraylarch', 'tmp.pkg']' died with <Signals.SIGSEGV: 11>.
ClinamenPY3:conda_constructor>

```

I've never seen that one before -- again I'm using a recipe that worked two weeks ago with master `constructor` and `conda 4.5.13`.  Any ideas what would cause that message from `productbuild`?


I'm still confused about why `constructor` cannot determine a default value for `conda_exe` an why it must be explicitly set.  `constructor` *is* intimately related to `conda`, it uses `$HOME\.conda` for building, and `constructor` is right there next to `conda` in the bin folder.  Is it unreasonable to use that as a default?   Like, when would it ever make sense to use a different  `conda_exe`?

**Comment by nehaljwani** [comment]
@newville Could you please share your construct.yaml file so that I can try and reproduce this problem?

**Comment by newville** [comment]
@nehaljwani I played around with this a little bit and made some progress and have a few more details.   First, building a shell installer for MacOS seems to always work fine, so the problem does appear to be only with the MacOS package installer.

The `construct.yaml` below fails with the message from `productbuild`.  Admittedly the script is large with lots of dependencies and I am not sure I would be able to justify needing all of these.  Some may have been accrued to fix older problems that have since been fixed by better means.  

I noticed that removing the `anaconda` package allows the package installer to be built.   I do not know why that is.  The packaged apps appear to run OK when installed though I have not done thorough testing.  

I don't know what packages anaconda brings in that would cause the problem. I'm not sure the problem is truly solved or just being avoided for the time being....
 


Anyway, this uses a custom anaconda.org channel.  it works to build a shell installer on MacOS, but not a package installer:

```
name:  xraylarch
version: 0.9.45

channels:
    - https://repo.continuum.io/pkgs/main
    - https://repo.continuum.io/pkgs/msys2 [win]
    - https://conda.anaconda.org/gsecars/

ignore_duplicate_files: True

installer_type: pkg [osx]

specs:
    - python>=3.7
    - conda
    - setuptools
    - pip
    - openssl
    - asn1crypto
    - anaconda
    - numpy>=1.16
    - scipy>=1.2
    - matplotlib
    - yaml
    - termcolor
    - pcre
    - pyyaml
    - psutil
    - requests
    - cython
    - h5py
    - pillow
    - sqlalchemy
    - psycopg2
    - scikit-image
    - scikit-learn
    - pandas
    - patchelf         # [linux]
    - pango            # [linux]
    - fontconfig       # [linux or osx]
    - readline         # [linux or osx]
    - python.app       # [osx]
    - pywin32          # [win64]
    - console_shortcut # [win64]
    - powershell_shortcut # [win64]
    - pyqtgraph
    - wxpython
    - pycifrw
    - peakutils
    - pyshortcuts
    - pyepics
    - lmfit
    - asteval
    - wxutils
    - wxmplot
    - tomopy
    - dioptas
    - pyFAI
    - fabio
    - silx
    - tifffile
    - xraylarch
```

**Comment by AXGKl** [comment]
@nehaljwani @mingwandroid  just wanted to say that I'm really really happy again, with your work for v3.
I see that @newville still faces problems but on and for Linux I I had not a single failure the last days and was trying different stuffs... even have the feeling that it's running through significantly faster (can that be?) than before.
And the noarch support is fantastic, will save us a lot of time when building the upstream packages
Last weeks were though but I'm one happy camper again :-)
Thanks a lot.

**Comment by newville** [comment]
@nehaljwani @mingwandroid @AXGKl just to be clear, I think things are working much better too, and Thanks!   I agree that supporting `noarch` and `.conda` are very helpful.  I did run into  a few issues but I think I have a workaround.   Reporting them fully here is just to try to help others who might run into similar issues.

**Comment by mingwandroid** [comment]
Great to hear everyone. And thanks for helping us to improve.

**Comment by nehaljwani** [comment]
@newville I have seen the problem you are facing before. This happens due to restriction on the maximum number of open files per process. Look at the value of `ulimit -n`. Your example fails for a low value, but succeeds for a higher value (I tested 512 and 2048 respectively).
